const maizuruRoutesData = [
{
  "route_id": "route_01",
  "category": "nonbiri",
  "category_name_ja": "のんびり",
  "category_name_en": "Relaxed",
  "category_name_ko": "느긋한",
  "category_name_zh": "悠闲",
  "title_ja": "焼肉＆カフェで満腹コース",
  "title_en": "Yakiniku & Cafe Full Course",
  "title_ko": "야키니쿠 & 카페 배부른 코스",
  "title_zh": "烤肉与咖啡厅饱足路线",
  "description_ja": "個室焼肉「味道楽」で焼肉を楽しんだ後、カフェでコーヒーやケーキを堪能できるコースです！",
  "description_en": "Enjoy yakiniku at private-room restaurant \"Midoraku\" and then relax with coffee and cake at a cafe.",
  "description_ko": "개인실 야키니쿠 '미도라쿠'에서 야키니쿠를 즐긴 후 카페에서 커피와 케이크를 즐길 수 있는 코스입니다!",
  "description_zh": "在包间烤肉店“味道乐”享用烤肉后，再到咖啡厅品尝咖啡和蛋糕的路线！",
  "distance_km": 1,
  "time_min": 5,
  "difficulty": "★☆☆",
  "waypoints": [
    "node_1779165554120",
    "J001161862",
    "J000505743"
  ]
},
{
  "route_id": "route_02",
  "category": "history",
  "category_name_ja": "歴史探訪",
  "category_name_en": "History Tour",
  "category_name_ko": "역사 탐방",
  "category_name_zh": "历史探访",
  "title_ja": "観光名所巡り＆鉄板焼きコース",
  "title_en": "Landmark Tour & Teppanyaki Course",
  "title_ko": "명소 순회 & 철판구이 코스",
  "title_zh": "名胜巡游与铁板烧路线",
  "description_ja": "東舞鶴の観光名所「赤れんがパーク・博物館」を巡ったあと、鉄板焼き「バンビ」で広島風お好み焼きを楽しむことができるコースです！",
  "description_en": "Tour Higashi Maizuru landmarks such as Red Brick Park and Museum, then enjoy Hiroshima-style okonomiyaki at teppanyaki restaurant Bambino.",
  "description_ko": "히가시 마이즈루의 명소인 '아카렌가 파크·박물관'을 둘러본 뒤 철판구이 '밤비'에서 히로시마식 오코노미야키를 즐길 수 있는 코스입니다!",
  "description_zh": "游览东舞鹤的人气景点“赤砖公园·博物馆”，之后在铁板烧“Bambi”品尝广岛风御好烧的路线！",
  "distance_km": 3,
  "time_min": 30,
  "difficulty": "★★☆",
  "waypoints": [
    "node_1779165554120",
    "way_183842148",
    "way_43881285",
    "J003686006"
  ]
},
{
  "route_id": "route_03",
  "category": "active",
  "category_name_ja": "アクティブ",
  "category_name_en": "Active",
  "category_name_ko": "액티브",
  "category_name_zh": "活力",
  "title_ja": "カジュアルフレンチ＆公園コース",
  "title_en": "Casual French & Park Course",
  "title_ko": "캐주얼 프렌치 & 공원 코스",
  "title_zh": "休闲法式与公园路线",
  "description_ja": "お洒落なビストロでフレンチ料理を楽しんだあと、海の見える前島みなと公園でまったりできるコースです！",
  "description_en": "Enjoy French cuisine at a stylish bistro, then relax at Maejima Minato Park with sea views.",
  "description_ko": "세련된 비스트로에서 프렌치 요리를 즐긴 후 바다 전망의 마에시마 미나토 공원에서 여유를 즐길 수 있는 코스입니다!",
  "description_zh": "在时尚小酒馆享用法式料理后，于可眺望海景的前岛港口公园悠闲散步的路线！",
  "distance_km": 2,
  "time_min": 20,
  "difficulty": "★★☆",
  "waypoints": [
    "node_1779165554120",
    "J003736064",
    "way_563048948"
  ]
},
{
  "route_id": "route_04",
  "category": "active",
  "category_name_ja": "アクティブ",
  "category_name_en": "Active",
  "category_name_ko": "액티브",
  "category_name_zh": "活力",
  "title_ja": "イタリアン＆青葉山ろく公園コース",
  "title_en": "Italian & Aobayama Hill Park Course",
  "title_ko": "이탈리안 & 아오바야마 공원 코스",
  "title_zh": "意大利料理与青叶山公园路线",
  "description_ja": "「モルト・ヴォーノ・ニーナ」で本格イタリアンを楽しんだ後、青葉青ろく公園で遊べるルートです！",
  "description_en": "Enjoy authentic Italian cuisine at Molto Buono Nina, then spend time at Aobayama Hill Park.",
  "description_ko": "'몰토 보노 니나'에서 정통 이탈리안을 즐긴 후 아오바야마 공원에서 즐길 수 있는 코스입니다!",
  "description_zh": "先在“Molto Buono Nina”享受正宗意大利料理，再到青叶山公园玩耍的路线！",
  "distance_km": 7,
  "time_min": 30,
  "difficulty": "★★★",
  "waypoints": [
    "node_1779165554120",
    "J000776415",
    "way_563042956"
  ]
},
{
  "route_id": "route_05",
  "category": "love",
  "category_name_ja": "愛",
  "category_name_en": "Love",
  "category_name_ko": "러브",
  "category_name_zh": "爱情",
  "title_ja": "2人ならどこへでも行ける、愛に満ちたラブラブコース",
  "title_en": "just the two of us, a love-filled lovey-dovey course",
  "title_ko": "둘이서라면 어디든 갈 수 있는, 사랑이 가득한 러브러브 코스",
  "title_zh": "两个人就能去任何地方，充满爱的甜蜜路线",
  "description_ja": "",
  "description_en": "",
  "description_ko": "",
  "description_zh": "",
  "distance_km": 0,
  "time_min": 0,
  "difficulty": "love solve all",
  "waypoints": [
    "node_temp",
    "temp",
    "way_temp"
  ]
}
];
